import { Document, Packer, Paragraph } from 'docx'
import * as XLSX from 'xlsx'
import { saveAs } from 'file-saver'
import type { Deal, Extraction, Finding } from '@/lib/types'

function safeFilename(name: string) {
  return name.replace(/[^\w\-]+/g, '_').replace(/_+/g, '_').slice(0, 80) || 'report'
}

export async function downloadDealSummaryDocx(params: {
  deal: Deal
  findings: Finding[]
  extractions: Extraction[]
}) {
  const { deal, findings, extractions } = params
  const accepted = extractions.filter((e) => e.status === 'accepted' || e.status === 'edited')
  const topFindings = findings.slice(0, 40)

  const lines: string[] = [
    'Insurance diligence summary (demo export)',
    '',
    deal.name,
    `Target: ${deal.targetCompany}`,
    `Acquirer: ${deal.acquirer}`,
    '',
    'Accepted extractions',
    ...accepted.slice(0, 35).map(
      (e) => `${e.fieldName}: ${e.value} (confidence ${Math.round(e.confidence * 100)}%)`
    ),
    '',
    'Findings',
    ...topFindings.map(
      (f) => `[${f.severity}] ${f.title} — ${f.description.replace(/\s+/g, ' ').slice(0, 400)}`
    ),
    '',
    'Generated by Hauser diligence (demo). Not for client distribution without review.',
  ]

  const doc = new Document({
    sections: [{ children: lines.map((t) => new Paragraph(t)) }],
  })
  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${safeFilename(deal.name)}-summary.docx`)
}

export function downloadDealSummaryXlsx(params: {
  deal: Deal
  findings: Finding[]
  extractions: Extraction[]
}) {
  const { deal, findings, extractions } = params
  const accepted = extractions.filter((e) => e.status === 'accepted' || e.status === 'edited')

  const summaryRows = [
    { Field: 'Deal', Value: deal.name },
    { Field: 'Target', Value: deal.targetCompany },
    { Field: 'Acquirer', Value: deal.acquirer },
    { Field: 'Accepted extractions', Value: String(accepted.length) },
    { Field: 'Findings', Value: String(findings.length) },
  ]
  const findingRows = findings.map((f) => ({
    Severity: f.severity,
    Status: f.status,
    Title: f.title,
    Description: f.description.slice(0, 500),
    RuleId: f.ruleId ?? '',
  }))
  const extRows = accepted.map((e) => ({
    Field: e.fieldName,
    Category: e.fieldCategory,
    Value: e.value,
    Confidence: e.confidence,
    Status: e.status,
  }))

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summaryRows), 'Summary')
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(findingRows), 'Findings')
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(extRows), 'Extractions')
  const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'array' }) as Uint8Array
  saveAs(
    new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    `${safeFilename(deal.name)}-summary.xlsx`
  )
}
