import type { Deal, Document, Extraction, Finding, DRLItem, ActivityLog, DRLStatus, PracticeLine } from '../types'
import { getDRLTemplateForPracticeLine } from './drl-template'

export function generateDemoData() {
  const now = new Date()
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)
  const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)

  const deals: Deal[] = [
    {
      id: 'deal-1',
      name: 'Project Hawkeye',
      targetCompany: 'Midwest Specialty Manufacturing LLC',
      acquirer: 'Silver Ridge Equity Partners',
      status: 'active',
      phase: 'due_diligence',
      description:
        'Insurance diligence for a multi-state manufacturing platform: GL, auto, WC, and employee health benefits.',
      dealValue: 185000000,
      createdAt: monthAgo.toISOString(),
      updatedAt: weekAgo.toISOString(),
      assignedAnalysts: ['user-2', 'user-3'],
      createdBy: 'user-1',
      practiceLine: 'both',
      industry: 'Manufacturing',
      geography: 'US — Midwest & Southeast',
      specialExposures: ['Legacy asbestos / products liability', 'Self-funded medical (ASO)', 'Multi-state WC'],
      broker: 'Marsh McLennan (retail)',
      revenue: 420000000,
      ebitda: 61000000,
    },
    {
      id: 'deal-2',
      name: 'Project Cedar',
      targetCompany: 'Regional Staffing Holdings Inc.',
      acquirer: 'Harbor Point Capital',
      status: 'active',
      phase: 'preliminary',
      description: 'Benefits-heavy diligence for a PE-backed staffing rollup.',
      dealValue: 42000000,
      createdAt: weekAgo.toISOString(),
      updatedAt: now.toISOString(),
      assignedAnalysts: ['user-2'],
      createdBy: 'user-1',
      practiceLine: 'benefits',
      industry: 'Staffing & HR services',
      geography: 'US — National',
      specialExposures: ['PEO / ASO structures', 'ACA affordability'],
      broker: 'Willis Towers Watson',
      revenue: 128000000,
      ebitda: 14200000,
    },
    {
      id: 'deal-3',
      name: 'Project Granite',
      targetCompany: 'Summit Civil Contractors LLC',
      acquirer: 'Northline Growth Partners',
      status: 'completed',
      phase: 'completed',
      description: 'Completed P&C diligence for a construction services platform.',
      dealValue: 96000000,
      createdAt: new Date(now.getTime() - 120 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: monthAgo.toISOString(),
      assignedAnalysts: ['user-3'],
      createdBy: 'user-1',
      practiceLine: 'pc',
      industry: 'Construction',
      geography: 'US — Mountain West',
      specialExposures: ['Wrap-up / OCIP programs', 'Surety dependency'],
      broker: 'Aon Construction',
      revenue: 210000000,
      ebitda: 22400000,
    },
  ]

  const documents: Document[] = [
    {
      id: 'doc-1',
      dealId: 'deal-1',
      name: 'GL_Auto_Umbrella_DecPages_2024-2025.pdf',
      type: 'pdf',
      category: 'policy_documents',
      status: 'ready',
      uploadedAt: weekAgo.toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/gl-auto-umbrella.pdf',
      fileSize: 1820000,
      pageCount: 38,
      ocrProcessed: false,
      classificationConfidence: 0.96,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-2',
      dealId: 'deal-1',
      name: 'WC_GL_Loss_Run_10Y_by_Accident_Year.pdf',
      type: 'pdf',
      category: 'loss_runs',
      status: 'ready',
      uploadedAt: weekAgo.toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/loss-run-10y.pdf',
      fileSize: 920000,
      pageCount: 14,
      ocrProcessed: false,
      classificationConfidence: 0.94,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-3',
      dealId: 'deal-1',
      name: 'Broker_Market_Submission_Summary_2025.xlsx',
      type: 'xlsx',
      category: 'broker_proposals',
      status: 'ready',
      uploadedAt: weekAgo.toISOString(),
      uploadedBy: 'user-3',
      blobUrl: '/demo/broker-submission.xlsx',
      fileSize: 210000,
      pageCount: 6,
      ocrProcessed: false,
      classificationConfidence: 0.91,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-9',
      dealId: 'deal-1',
      name: 'Audited_Financial_Statements_2022-2024.pdf',
      type: 'pdf',
      category: 'financial_statements',
      status: 'ready',
      uploadedAt: weekAgo.toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/audited-financials.pdf',
      fileSize: 4100000,
      pageCount: 52,
      ocrProcessed: false,
      classificationConfidence: 0.94,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-10',
      dealId: 'deal-1',
      name: 'Claims_Detail_Triangle_5Y.pdf',
      type: 'pdf',
      category: 'claims_history',
      status: 'ready',
      uploadedAt: weekAgo.toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/claims-detail.pdf',
      fileSize: 890000,
      pageCount: 11,
      ocrProcessed: false,
      classificationConfidence: 0.91,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-4',
      dealId: 'deal-1',
      name: 'Active_Enrollment_Census_PlanYear2025.xlsx',
      type: 'xlsx',
      category: 'census_files',
      status: 'ready',
      uploadedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/enrollment-census.xlsx',
      fileSize: 480000,
      pageCount: 1,
      ocrProcessed: false,
      classificationConfidence: 0.97,
      phiSensitivity: 'phi',
    },
    {
      id: 'doc-5',
      dealId: 'deal-1',
      name: 'Form5500_Medical_2023_signed.pdf',
      type: 'pdf',
      category: 'erisa_documents',
      status: 'ready',
      uploadedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/form5500-medical.pdf',
      fileSize: 1100000,
      pageCount: 24,
      ocrProcessed: false,
      classificationConfidence: 0.93,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-6',
      dealId: 'deal-1',
      name: 'RxDC_P2_Submission_Package_2024.pdf',
      type: 'pdf',
      category: 'rxdc',
      status: 'ready',
      uploadedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      uploadedBy: 'user-3',
      blobUrl: '/demo/rxdc-package.pdf',
      fileSize: 760000,
      pageCount: 18,
      ocrProcessed: false,
      classificationConfidence: 0.9,
      phiSensitivity: 'phi',
    },
    {
      id: 'doc-7',
      dealId: 'deal-2',
      name: 'SPD_Medical_Dental_2024.pdf',
      type: 'pdf',
      category: 'benefits_plans',
      status: 'ready',
      uploadedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/spd-medical-dental.pdf',
      fileSize: 2400000,
      pageCount: 86,
      ocrProcessed: false,
      classificationConfidence: 0.95,
      phiSensitivity: 'non_phi',
    },
    {
      id: 'doc-8',
      dealId: 'deal-2',
      name: 'WC_Payroll_ClassCodes_Q4_2024.xlsx',
      type: 'xlsx',
      category: 'wc_payroll_reports',
      status: 'ready',
      uploadedAt: now.toISOString(),
      uploadedBy: 'user-2',
      blobUrl: '/demo/wc-payroll-q4.xlsx',
      fileSize: 198000,
      pageCount: 3,
      ocrProcessed: false,
      classificationConfidence: 0.92,
      phiSensitivity: 'non_phi',
    },
  ]

  const extractions: Extraction[] = [
    {
      id: 'ext-1',
      documentId: 'doc-1',
      dealId: 'deal-1',
      fieldName: 'General Aggregate (GL)',
      fieldCategory: 'P&C — Limits',
      value: '$2,000,000',
      originalValue: '$2,000,000',
      confidence: 0.95,
      pageRef: 3,
      sourceText: 'General Aggregate Limit: $2,000,000',
      status: 'accepted',
      reviewedBy: 'user-2',
      reviewedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'ext-2',
      documentId: 'doc-2',
      dealId: 'deal-1',
      fieldName: '10-year loss ratio (WC)',
      fieldCategory: 'P&C — Loss',
      value: '68%',
      originalValue: '68%',
      confidence: 0.9,
      pageRef: 2,
      sourceText: 'Loss Ratio (WC): 68%',
      status: 'accepted',
      reviewedBy: 'user-2',
      reviewedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'ext-3',
      documentId: 'doc-4',
      dealId: 'deal-1',
      fieldName: 'Total enrolled employees',
      fieldCategory: 'Benefits — Census',
      value: '1,842',
      originalValue: '1,842',
      confidence: 0.98,
      pageRef: 1,
      status: 'pending',
    },
    {
      id: 'ext-4',
      documentId: 'doc-4',
      dealId: 'deal-1',
      fieldName: 'Self-funded vs fully insured (medical)',
      fieldCategory: 'Benefits — Plan design',
      value: 'Self-funded (ASO)',
      originalValue: 'Self-funded (ASO)',
      confidence: 0.82,
      pageRef: 1,
      status: 'pending',
    },
    {
      id: 'ext-5',
      documentId: 'doc-6',
      dealId: 'deal-1',
      fieldName: 'RxDC filing deadline met (2024)',
      fieldCategory: 'Benefits — RxDC',
      value: 'Yes — filed 6/1/2024',
      originalValue: 'Yes — filed 6/1/2024',
      confidence: 0.86,
      pageRef: 4,
      status: 'pending',
    },
  ]

  const findings: Finding[] = [
    {
      id: 'finding-1',
      dealId: 'deal-1',
      documentId: 'doc-2',
      sourceExtractionId: 'ext-2',
      type: 'risk',
      severity: 'high',
      status: 'open',
      title: 'Elevated WC loss trend in legacy plants',
      description:
        'Loss development shows rising frequency in two legacy facilities. Recommend targeted safety audit and IBNR stress test before close.',
      pageRef: 2,
      ruleId: 'wc-loss-trend',
      notes: [],
      createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'user-2',
      assignedTo: 'user-3',
      reviewWorkflow: 'under_review',
    },
    {
      id: 'finding-2',
      dealId: 'deal-1',
      documentId: 'doc-1',
      type: 'gap',
      severity: 'medium',
      status: 'acknowledged',
      title: 'Umbrella follow-form confirmation',
      description:
        'Umbrella dec page references follow-form GL; confirm auto follow-form and scheduled underlying attachment matches broker SOV.',
      pageRef: 5,
      ruleId: 'umbrella-follow-form',
      notes: [],
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'user-3',
      assignedTo: 'user-2',
      reviewWorkflow: 'approved',
    },
    {
      id: 'finding-3',
      dealId: 'deal-1',
      type: 'gap',
      severity: 'medium',
      status: 'open',
      title: 'Missing stop-loss carrier financials',
      description:
        'ASO medical is indicated on census; stop-loss agreements and carrier ratings not yet in the data room.',
      notes: [],
      createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'user-3',
      assignedTo: 'user-2',
      reviewWorkflow: 'pending_docs',
    },
    {
      id: 'finding-4',
      dealId: 'deal-1',
      documentId: 'doc-6',
      type: 'observation',
      severity: 'info',
      status: 'open',
      title: 'RxDC submission package complete',
      description: 'P2 reporting package present for plan year 2024; no immediate compliance flags from file index.',
      pageRef: 1,
      notes: [],
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'user-3',
      assignedTo: 'user-3',
      reviewWorkflow: 'approved',
    },
    {
      id: 'finding-5',
      dealId: 'deal-1',
      type: 'alert',
      severity: 'high',
      status: 'open',
      title: 'PHI census stored outside secure workspace',
      description:
        'Enrollment census contains PHI. Confirm restricted access, encryption at rest, and BAA coverage for any third-party processors.',
      pageRef: 1,
      notes: [
        {
          id: 'note-2',
          content: 'Team Lead: route census to secure PHI lane and confirm client redaction policy.',
          createdBy: 'user-3',
          createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
      ],
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'user-3',
      assignedTo: 'user-3',
      reviewWorkflow: 'blocked',
    },
  ]

  const matchersDeal1: {
    test: (t: Omit<DRLItem, 'id' | 'dealId'>) => boolean
    status: DRLStatus
    documentId?: string
  }[] = [
    { test: (t) => t.documentName.includes('Audited financial'), status: 'complete', documentId: 'doc-9' },
    { test: (t) => t.documentName.includes('P&C policies'), status: 'complete', documentId: 'doc-1' },
    { test: (t) => t.documentName.includes('Loss runs'), status: 'complete', documentId: 'doc-2' },
    { test: (t) => t.documentName.includes('Claims detail'), status: 'complete', documentId: 'doc-10' },
    { test: (t) => t.documentName.includes('Broker market'), status: 'complete', documentId: 'doc-3' },
    { test: (t) => t.documentName.includes('Active employee census'), status: 'complete', documentId: 'doc-4' },
    { test: (t) => t.documentName.includes('Form 5500'), status: 'under_review', documentId: 'doc-5' },
    { test: (t) => t.documentName.includes('RxDC'), status: 'complete', documentId: 'doc-6' },
    { test: (t) => t.priority === 'required', status: 'requested' },
  ]

  const drlItems: DRLItem[] = getDRLTemplateForPracticeLine('both').map((template, index) => {
    const match = matchersDeal1.find((m) => m.test(template))
    const status = match?.status ?? 'not_requested'
    const documentId = match?.documentId
    const receivedAt =
      status === 'complete' || status === 'under_review' || status === 'received'
        ? weekAgo.toISOString()
        : undefined
    return {
      ...template,
      id: `drl-1-${index}`,
      dealId: 'deal-1',
      status,
      documentId,
      receivedAt,
      requestedAt: status !== 'not_requested' ? weekAgo.toISOString() : undefined,
    }
  })

  const deal2Template = getDRLTemplateForPracticeLine('benefits' as PracticeLine)
  const deal2DrlItems: DRLItem[] = deal2Template.map((template, index) => {
    let status: DRLStatus = index < 4 ? 'requested' : 'not_requested'
    let documentId: string | undefined
    let receivedAt: string | undefined
    if (template.documentName.includes('SPD')) {
      status = 'complete'
      documentId = 'doc-7'
      receivedAt = weekAgo.toISOString()
    }
    return {
      ...template,
      id: `drl-2-${index}`,
      dealId: 'deal-2',
      status,
      documentId,
      receivedAt,
      requestedAt: status !== 'not_requested' ? weekAgo.toISOString() : undefined,
    }
  })

  const deal3Template = getDRLTemplateForPracticeLine('pc')
  const deal3DrlItems: DRLItem[] = deal3Template.map((template, index) => ({
    ...template,
    id: `drl-3-${index}`,
    dealId: 'deal-3',
    status: 'complete' as DRLStatus,
    documentId: undefined,
    receivedAt: monthAgo.toISOString(),
    requestedAt: monthAgo.toISOString(),
  }))

  const activityLogs: ActivityLog[] = [
    {
      id: 'log-1',
      dealId: 'deal-1',
      userId: 'user-2',
      action: 'uploaded',
      details: 'Uploaded GL_Auto_Umbrella_DecPages_2024-2025.pdf',
      entityType: 'document',
      entityId: 'doc-1',
      createdAt: weekAgo.toISOString(),
    },
    {
      id: 'log-2',
      dealId: 'deal-1',
      userId: 'user-2',
      action: 'reviewed',
      details: 'Approved extraction: General Aggregate (GL)',
      entityType: 'extraction',
      entityId: 'ext-1',
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'log-3',
      dealId: 'deal-1',
      userId: 'user-3',
      action: 'created',
      details: 'Created finding: Elevated WC loss trend in legacy plants',
      entityType: 'finding',
      entityId: 'finding-1',
      createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'log-4',
      dealId: 'deal-1',
      userId: 'user-2',
      action: 'added_note',
      details: 'Added note to finding: PHI census handling',
      entityType: 'finding',
      entityId: 'finding-5',
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'log-5',
      dealId: 'deal-2',
      userId: 'user-1',
      action: 'created',
      details: 'Created deal: Project Cedar',
      entityType: 'deal',
      entityId: 'deal-2',
      createdAt: weekAgo.toISOString(),
    },
  ]

  return {
    deals,
    documents,
    extractions,
    findings,
    drlItems: [...drlItems, ...deal2DrlItems, ...deal3DrlItems],
    activityLogs,
  }
}
